### PR TITLE
fix(rbac): do not create clusterrole for namespace deployment on Traefik v3

### PR DESCRIPTION
**Pull request by ChandonPierre**
A namespace scoped deployment should not create cluster scoped rbac.

### CODE REVIEW

**Comment by mloiseleur** [comment]
@ChandonPierre Thanks. You found an interesting way for rbac namespaced. 

Would you please add test and some documentation in values.yaml ?

**Review by darkweaver87 — CHANGES_REQUESTED** [review]
This PR only works with traefik v3.0.0.
Please update your if statements and your tests accordingly by adding something like:
`{{- if semverCompare "<3.0.0-0" (include "imageVersion" $) }}`

**Comment by mloiseleur** [comment]
@ChandonPierre In its current form, this PR will be breaking for v3 users, using spec.ingressClassname with `rbac.namespaced` enabled. They will be forced to add annotations.

Wdyt about:
1. Introducing this new `provider.kubernetesIngress.disableIngressClassLookup` in values for v3 users
2. When both `provider.kubernetesIngress.disableIngressClassLookup` and `rbac.namespaced` are set, then it won't generate `ClusterRole`

**Review by mloiseleur — APPROVED** [review]
Thanks :+1: LGTM

**Review by darkweaver87 — APPROVED** [review]
LGTM.
I tested it, it works well, thanks for your contribution :-)

**Pull request merged**
