### PR TITLE
Add an option to disable dashboard

### PR DESCRIPTION
**Pull request by elthariel**
Part 2 of #26

### CODE REVIEW

**Comment by ldez** [comment]
This PR need to be rebase because of  #35

**Comment by elthariel** [comment]
#35 breaks my setup, so not really motivated haha

**Comment by elthariel** [comment]
On a side note, I'm wondering why the ingress is installed with a hook ? iirc, it means the resource isn't deleted when removing the release and prevent re-installing it

**Comment by dduportal** [comment]
If you want @elthariel , I can take care of this: I thought your PR would be merged before mine (sorry for that) 😅 

> On a side note, I'm wondering why the ingress is installed with a hook ? 
If you install on a scratch cluster, as the dashboard requires an `IngressRoute` object to be created, it means that there is a precedence with the CRDS that must be installed first. So we need a hook to be sure that Helm create the `IngressRoute` only when the Kube API is ready for it.

> iirc, it means the resource isn't deleted when removing the release and prevent re-installing it

Good point. We might want to add a hook delete policy as in https://v3.helm.sh/docs/topics/charts_hooks/#hook-resources-are-not-managed-with-corresponding-releases .

**Comment by dduportal** [comment]
@elthariel thanks a LOT for your work and feedback. I took the freedom to rebase this PR against master, and remove the `dashboard.service` part as it is not needed anymore. WDYT?

**Comment by dduportal** [comment]
Latest test:

- Default install let me access the dashboard 👍 (ingress created as before)
- Install with `helm install --name=traefik --set=dashboard.ingress.enabled=false .` works (Traefik is functional), but no Ingress exposed 👍 

I'm not LGTM-ing this PR as I co-contributed :)

**Comment by ldez** [comment]
seems a bit confusing with `- "--api.dashboard=true"`

**Comment by dduportal** [comment]
@ldez I'm not sure to understand? Are you saying we should keep the same naming in the `values.yaml` as in Traefik alone?

**Comment by ldez** [comment]
- `.Values.dashboard.ingress.enabled` add a IngressRoute, so the word `ingress` seems weird.
- `- "--api.dashboard=true"` is not configurable.

**Comment by dduportal** [comment]
> Values.dashboard.ingress.enabled add a IngressRoute, so the word ingress seems weird.

Good catch, thanks!

> - "--api.dashboard=true" is not configurable.
> If I follow the PR title ("Add an option to disable dashboard") there is something missing.

Fair. WDYt about the following values?

```yml
dashboard:
  # Enable the dashboard on Traefik
  enable: true

  # Expose the dashboard and api through an ingress route at /dashboard
  # and /api This is not secure and SHOULD NOT be enabled on production
  # deployments
  ingressroute: true
```

**Comment by ldez** [comment]
I agree :+1: 

`ingressroute` -> `ingressRoute`

**Pull request merged**
