### PR TITLE
Add volume/volumeMounts and config.path property to yaml-section of values.yaml

### LINKED ISSUE #14: Be able to specify volumes and --configfile flag
In order to be able to use custom config-file from a config-map or secret it would be nice to be able to specify volumes/volumeMounts for deployment resource and --configfile="" argument in deployment args.

### PR DESCRIPTION
**Pull request by frelon**
Fixes #14

### CODE REVIEW

**Comment by frelon** [comment]
Example config (using empty-dir instead of config-map):

```yaml
## Default values for Traefik
image:
  name: traefik
  tag: 2.0.2
#
deployment:
  replicas: 1
#
ports:
  web:
    port: 8000
  websecure:
    port: 8443
  traefik:
    port: 9000
#
logs:
  loglevel: INFO
#
yaml:
  resources:
    requests:
      cpu: "100m"
      memory: "50Mi"
    limits:
      cpu: "300m"
      memory: "150Mi"
  volumes:
  - name: config
    emptyDir: {}
  volumeMounts:
  - name: config
    mountPath: /config
#
config:
  path: /config/traefik-config.toml
```

**Comment by crhuber** [comment]
Would this also work if one wanted to create a file provider?

**Comment by frelon** [comment]
Sure, as long as the file is in the config-map one could reference it from the main config-file.

**Comment by jasperkuperus** [comment]
Ok, I would like this behavior very much. I was at the point of creating a PR for `volumes` and `volumeMounts`. It's very useful for mounting secrets, e.g. when you want to configure Let's Encrypt with Google Cloud DNS and want to mount a service account.

The PR looks good to me. The only thing I don't understand is: Why namespace these under `yaml`, while e.g. `ports`, `env`, etc. are on top level in `values.yaml`?

What's the status of this PR?

**Comment by mmatur** [comment]
Hi @frelon 

Thanks for your contribution. 

I will close your PR in favor of #84

Duplicate of #84

**Pull request closed without merging**
