### PR TITLE
Add image pull policy

### PR DESCRIPTION
**Pull request by j3r0lin**
This PR add option `image.pullPolicy` to allow setting traefik app deployment container `imagePullPolicy` value, defaults to `IfNotPresent`.

### CODE REVIEW

**Comment by SantoDE** [comment]
Hey @j3r0lin,

thanks for your contribution.

Could you please add a proper description to your PR and bump the version on the chart? Otherwise the build will fail.

**Comment by j3r0lin** [comment]
@SantoDE updated, please review again.

**Comment by SantoDE** [comment]
Thanks. We should wait for #221 to be merged first, then update the the versions here one last time and merge then. Sounds good to you?

**Comment by j3r0lin** [comment]
ok, let me know if #221 merged.

**Comment by SantoDE** [comment]
Merged @j3r0lin.

Once you've fixed the conflict, we're good to go

**Comment by j3r0lin** [comment]
@SantoDE sorry for the delay, I have updated the branch, but the travis job failed cause of installing helm client.

**Pull request merged**
