### PR TITLE
feat: release v27.0.1 with Traefik Proxy to v2.11.1

### PR DESCRIPTION
**Pull request by mloiseleur**
# What does it do ?

Publish a new release with Traefik Proxy to v2.11.1

# Motivation

It comes with many bugfixes, see upstream [release notes](https://github.com/traefik/traefik/releases/tag/v2.11.1).

### CODE REVIEW

**Comment by dabeck** [comment]
This should also introduce the lingeringTimeout settings

**Comment by mloiseleur** [comment]
@dabeck: It can be set with `additionalArguments`. Feel free to open a PR if you need a full integration on this.

**Comment by dabeck** [comment]
> @dabeck: It can be set with `additionalArguments`.
> 
> Feel free to open a PR if you need a full integration on this.

Yes I know - I thought it might be good to make it more present here to point out this is a breaking change!

**Review by darkweaver87 — APPROVED** [review]
LGTM

**Comment by mloiseleur** [comment]
> > @dabeck: It can be set with `additionalArguments`.
> > Feel free to open a PR if you need a full integration on this.
> 
> Yes I know - I thought it might be good to make it more present here to point out this is a breaking change!

\o. I get it. Thanks, that's right it can in few cases. I'll update the PR.

**Comment by mloiseleur** [comment]
@dabeck I updated the changelog. Wdyt ?

**Comment by dabeck** [comment]
LGTM

**Pull request merged**
