### PR TITLE
Added persistent volume support.

### PR DESCRIPTION
**Pull request by trankchung**
This PR is to support persistent data so certificates are intact on pod restart.

### CODE REVIEW

**Comment by portswigger-tim** [comment]
This clearly restricts you to one replica when persistence is enabled 😬 - why did you not use StatefulSet with volumeClaimTemplate? 🤦

**Comment by zek** [comment]
> Why would you need more than one replica? The saved acme.json file is exactly the same on each persistent volume.

High Availability

**Comment by mloiseleur** [comment]
@portswigger-tim @ckt114 @zek Feel free to submit a PR if you think you can improve the current options on storage.

**Comment by zek** [comment]
> @portswigger-tim @ckt114 @zek Feel free to submit a PR if you think you can improve the current options on storage.

I've decided that I don't need volumes to store the certificates. I don't see any benefits. Therefore I stick with cert-manager.

**Pull request merged**
