### PR TITLE
feat(service): load balancer IP

### PR DESCRIPTION
**Pull request by anasinnyk**
Add the possibility to configure Load Balancer IP

### CODE REVIEW

**Comment by dduportal** [comment]
Hi @anasinnyk , do you think that #36 will solve your issue as well? (it aims to provide a more generic way to setup the service)

**Comment by anasinnyk** [comment]
@dduportal yes it's can resolve my issue

**Comment by dduportal** [comment]
Closing in favor of #36.

**Comment by dduportal** [comment]
Thanks a lot for your proposal and contribution !

**Pull request closed without merging**
